apiVersion: apdexone.com/v1alpha1
kind: XTest
metadata:
  name: project-buenafe
  labels:
    provider: k6
spec:
  id: project-buenafe
  compositionRef:
    name: test-k6
  parameters:
<<<<<<< HEAD:archivo-salida.yaml
    image: "norgefajardo/test-k6:oeuoeuoeuoeu
=======
    image: "norgefajardo/test-k6:f25fb51b81d4f7fcdd6bc6a344444fcce12d7421"
>>>>>>> 604b3a96c08e03d598432e936be335f764a5619c:apps/project-k6-test.yaml
    args: ["run","/tmp/script.js","-o","output-prometheus-remote"]
    schedule: "25 2 * * *"
    cpu: 100Mi
    memory: 28M
    pods: 3
    duration: 120
    namespace: production
