apiVersion: apdexone.com/v1alpha1
kind: XTest
metadata:
  name: project-buenafe
  labels:
    provider: k6
spec:
  id: project-buenafe
  compositionRef:
    name: test-k6
  parameters:
    image: "norgefajardo/test-k6:10c8e7309d31999f302db00c71e263d45ff92cd7"
    schedule: "20 5 * * 2"
    cpu: 100m
    memory: 28M
    pods: 2
    duration: 360
    namespace: production
