apiVersion: apdexone.com/v1alpha1
kind: XTest
metadata:
  name: project-orishas
  labels:
    provider: k6
spec:
  id: project-orishas
  compositionRef:
    name: test-k6
  parameters:
    image: "norgefajardo/test-k6:872a467c3e8bd9ff52c3a639946a2b9f5a5f0eff"
    args: ["run","/tmp/script.js","-o","output-prometheus-remote"]
    schedule: "30 2 * * *"
    cpu: 100m
    memory: 28M
    pods: 3
    duration: 120
    namespace: production
