apiVersion: apdexone.com/v1alpha1
kind: XTest
metadata:
  name: project-buenafe
  labels:
    provider: k6
spec:
  id: project-buenafe
  compositionRef:
    name: test-k6
  parameters:
    image: "norgefajardo/test-k6:7f1a66e08f705a2640b0db0a0d4be15c083a47f7"
    schedule: "25 3 * * *"
    cpu: 100m
    memory: 28M
    pods: 2
    duration: 360
    namespace: production
