apiVersion: apdexone.com/v1alpha1
kind: XTest
metadata:
  name: project-orishas
  labels:
    provider: k6
spec:
  id: project-orishas
  compositionRef:
    name: test-k6
  parameters:
    image: "norgefajardo/test-k6:5c8aad2ee6fce2bbaa0f8d7373af5034d78e8ec5"
    args: ["run","/tmp/script.js","-o","output-prometheus-remote"]
    schedule: "30 2 * * *"
    cpu: 100Mi
    memory: 28M
    pods: 3
    duration: 120
    namespace: production
