apiVersion: apdexone.com/v1alpha1
kind: XTest
metadata:
  name: project-sabina
  labels:
    provider: k6
spec:
  id: project-sabina
  compositionRef:
    name: test-k6
  parameters:
    image: "norgefajardo/test-k6:7d03fdcc29da8889d65d7b3ca9a1607e68b22462"
    schedule: "30 5 * * 2"
    cpu: 100m
    memory: 28M
    pods: 2
    duration: 360
    namespace: production
